name: Certify Changes

on:
  pull_request:
    branches: "*"
    paths:
      - "src/**"
      - "public/**"
      - "*.json"
      - "*.js"
      - "*.jsx"
      - "*.ts"
      - "*.tsx"

permissions:
  contents: read

jobs:
  certify:
    name: Certify Build Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Typecheck
        run: npm run check:ci

      - name: Run Jest
        run: npm run test:ci

      - name: Run Linter
        run: npm run lint:ci
