name: Lint Changes

on:
  workflow_dispatch:
  pull_request:
    branches: "*"
    paths:
      - "src/**"
      - "public/**"
      - "*.json"
      - "*.js"
      - "*.jsx"
      - "*.ts"
      - "*.tsx"

permissions:
  contents: read

jobs:
  lint:
    name: Lint Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4.0.1
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Typecheck
        run: npm run check:ci

      - name: Run Linter
        run: npm run lint:ci
