name: Spell Check

on:
  workflow_dispatch:
  push:
    branches:
      - "add-spellchecker"
  pull_request:
    branches: "*"
    paths:
      - "src/**"
      - "public/**"
      - "*.json"
      - "*.js"
      - "*.jsx"
      - "*.ts"
      - "*.tsx"

permissions:
  contents: write

jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.22

